### ISSUE TITLE
Admin > Events Timing Out

### ISSUE THREAD

**Issue by ds2600** [Lan2Play/eventula-manager#373]
Installed via standard Docker container (not compose). All Admin pages load just fine with no issues, when attempting to go to Admin > Events, the page eventually times out. I've never been able to actually _see_ the Events admin page. There are no events entered into the system currently.

MySQL server is hosted on the same server and as mentioned, all other admin pages load fine and reasonably fast.

Please let me know what other information you may need.

**Comment by Apfelwurm** [comment]
Hi @ds2600 
This problem is related to downtimes of Th0rn0s eventula.com site.
The eventula ecosystem was designed so that you can add your instance in your account on eventula.com and all your public events will be shown there as well. For that purpose you can give your event tags, that will be fetched from eventula.com as soon as you open the events page where you can add an event. If eventula.com is down (seems like that currently), this page takes minutes to load, but will work after that.

I've built a temporary "fix" for that:

When you don't need the eventula.com event tags, simply set 
```
EVENTULA_URL='DISABLE'
```

in your env instead of the eventula.com url.

**Comment by Apfelwurm** [comment]
3 times edited :D

**Comment by ds2600** [comment]
Perfect. Thank you! I currently am basically using it in "production", but simply as a static landing page as I get thing running again (long story). 

I'll definitely do that! Thank you!
