### ISSUE TITLE
Bug: npx mix missing permissions 

### ISSUE THREAD

**Issue by Mawiguk0** [Lan2Play/eventula-manager#526]
make app-build-clean-dev for example is not running because the permissions are set incorrectly.

Needs further description/ maybe fixed by dependency updates of npm

**Comment by Apfelwurm** [comment]
Lets discuss that in person the next days, if used like intended, there should be no problems. I have to invest time in documentation soon :D

**Comment by Apfelwurm** [comment]
In fact, i could reproduce the problem thanks to @TheR00st3r . So the problem was not on your side :D 
we will merge the fix soon and bring together our update and feature branches, so you can finnaly get your PR checked. see https://github.com/Lan2Play/eventula-manager/commit/e0e89231f7048fe32be098f6f8512725654a047a#diff-32fa976f0ea2ba7a4dff883ff6bc24966747a2586853dcdddfa0a9fed57c2b77
