### ISSUE TITLE
Tournament Registration before Event starts

### ISSUE THREAD

**Issue by Toutzn** [Lan2Play/eventula-manager#647]
If you plan an Event and add a tournament, I cannot find an option which allows registered and payed users to register the team before the Event starts. it is only possible if you change the event as public. but this is not what a all party will have.

is there an option which I didn't see?

**Comment by Apfelwurm** [comment]
I don't fully understand your question tbh but i try to explain what is going on here:

You have the visibility of your event, which does not do anything to the turnament registration. 
Also you have two different types of events, which are regular or online events.
On regular events you have to sign in participants (via admin panel / qr code/ entrance client), on online events you don't have to sign them in.

Then you have the status of your tournament. 

The tournament registration checks if the tournament is in the status OPEN and if the event participant is either signed in or if it is an online event. 
This makes sure on in person events, that only people that are really on the event can participate in the tournament.

**Comment by Toutzn** [comment]
Ok. The question exactly is: I added an onside event, no online event. And it will be nice that people can register the tournament before they check in onside. Means thy booked, payed and then they can register the team for the OPEN tournament.

**Comment by Apfelwurm** [comment]
Currently this is not implemented. Although it might seem like a small thing to implement that, due to several weird implementations this is not a trivial change on one place. But i think there is no reasons against the implementation, but this has to be done properly and with a lot of testing, since there are a lot of cases where this is handled differently. We can look into it, as soon as we manage to get https://github.com/Lan2Play/eventula-manager/pull/606 reviewed and merged, since this touches on some of the stuff nessecary. Also, this will  raise a similar problem as our oldest open issue https://github.com/Lan2Play/eventula-manager/issues/33 , because of that we have to rethink a good part of the whole participant/active participant logic in that case. So i can definitely say that this could not happen in the next weeks, if you have some kind of time constraints. What you theoretically should work (but be careful, it might also break things, i only tested it quickly) is that you create your event as an online event while you sell tickets and before you actually have your event, disable the online event setting. It will be shown nowhere as far as i know, and it only disables gifting tickets and will change that the event live view on the day of the event is accessable without the participants being signed in. But if you change it back right before the event, the live page should perform like expected only after the sign in.

**Comment by Apfelwurm** [comment]
Closed because of https://github.com/Lan2Play/eventula-manager/issues/972
