### ISSUE TITLE
Error message: "No Challonge Key Found"

### ISSUE THREAD

**Issue by daurpam** [Lan2Play/eventula-manager#834]
Hello!

I try to set the CHALLONGE_API_KEY, on docker-compose.yml and .env file, but when I check the Tournaments settings on web this message appears on the page. In the past I set this parameter without problems but I don't know if could be an issue on the latest versions.
In the log when start the container it seems that the variable is OK:
![image](https://github.com/user-attachments/assets/c4169afb-9e27-4267-88f5-db1bf36a394a)

Thanks in advance!

**Comment by daurpam** [comment]
Forget it, I've found that in settings-> API Keys, the API KEY could be set too.

**Comment by Apfelwurm** [comment]
@daurpam glad you found a Solution!
if you want to set the API keys via your ENV, you have to set ENV_OVERRIDE to true :)

`# ENV Overide If set to true, the App will take its API Keys from the ENV instead of the database. This includes Paypal, Stripe, Facebook, Challonge, Google Analytics, Facebook Analytics and Steam. With the default setting, you have to configure those credentials in the admin menu.
ENV_OVERRIDE=true`
